# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Monorepo

on:
  push:
    branches: [ "master" ]
    paths:
      - 'services/billing/**'
  pull_request:
    branches: [ "master" ]

jobs:

  build_billing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      working-directory: ./services/billing
      run: go build -v ./...

    - name: Test
      working-directory: ./services/billing
      run: go test -v ./...
